{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "ish-monitoring-mssqldb-exporter.fullname" . }}
  labels:
    app: {{ template "ish-monitoring-mssqldb-exporter.name" . }}
    chart: {{ template "ish-monitoring-mssqldb-exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "ish-monitoring-mssqldb-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "ish-monitoring-mssqldb-exporter.serviceAccountName" . }}
{{- end -}}
