{{- if .Values.mssql.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ish-monitoring-mssqldb-exporter.fullname" . }}
  labels:
    app: {{ template "ish-monitoring-mssqldb-exporter.name" . }}
    chart: {{ template "ish-monitoring-mssqldb-exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  mssql_password: {{ .Values.mssql.password | b64enc }}
{{- end -}}
